export interface ProvidersResponse {
    results: IProvider[]
}

export interface IProvider {
    display_priorities: DisplayPriorities
    display_priority: number
    logo_path: string
    provider_name: string
    provider_id: number
}

export interface DisplayPriorities {
    CA?: number
    AD?: number
    AE?: number
    AG?: number
    AL?: number
    AR?: number
    AT?: number
    AU?: number
    BA?: number
    BB?: number
    BE?: number
    BH?: number
    BM?: number
    BO?: number
    BS?: number
    BR?: number
    BG?: number
    CH?: number
    CI?: number
    CL?: number
    CO?: number
    CR?: number
    CU?: number
    CV?: number
    CZ?: number
    DE?: number
    DK?: number
    DO?: number
    DZ?: number
    EC?: number
    EE?: number
    EG?: number
    ES?: number
    FI?: number
    FJ?: number
    FR?: number
    GB?: number
    GF?: number
    GG?: number
    GH?: number
    GI?: number
    GQ?: number
    GR?: number
    GT?: number
    HK?: number
    HN?: number
    HR?: number
    HU?: number
    ID?: number
    IE?: number
    IL?: number
    IN?: number
    IQ?: number
    IS?: number
    IT?: number
    JM?: number
    JO?: number
    JP?: number
    KE?: number
    KR?: number
    KW?: number
    LB?: number
    LC?: number
    LI?: number
    LT?: number
    LV?: number
    LY?: number
    MA?: number
    MC?: number
    MD?: number
    MK?: number
    MT?: number
    MU?: number
    MX?: number
    MY?: number
    MZ?: number
    NE?: number
    NG?: number
    NL?: number
    NO?: number
    NZ?: number
    OM?: number
    PA?: number
    PE?: number
    PF?: number
    PH?: number
    PK?: number
    PL?: number
    PS?: number
    PT?: number
    PY?: number
    QA?: number
    RO?: number
    RS?: number
    SA?: number
    SC?: number
    SE?: number
    SI?: number
    SG?: number
    SN?: number
    SK?: number
    SM?: number
    SV?: number
    TC?: number
    TH?: number
    TN?: number
    TR?: number
    TT?: number
    TW?: number
    TZ?: number
    UG?: number
    US: number
    UY?: number
    VE?: number
    YE?: number
    ZA?: number
    ZM?: number
    AO?: number
    AZ?: number
    BY?: number
    BZ?: number
    CM?: number
    CY?: number
    LU?: number
    ME?: number
    MG?: number
    ML?: number
    TD?: number
    UA?: number
    ZW?: number
    NI?: number
    RU?: number
    XK?: number
    BF?: number
    CD?: number
    GY?: number
    PG?: number
    VA?: number
    MW?: number
}
